### ISSUE TITLE
configure fails if ~/.aws directory doesn't already exist

### ISSUE THREAD

**Issue by tjnicholas** [zl4bv/aws-session-credentials#13]
After providing an answer to "OATH credential name:" `aws-session configure` fails. If the `~/.aws` directory is created the command succeeds. 

```
/home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/lib/aws/session/credentials/file_provider/yaml_file_provider.rb:28:in `initialize': No such file or directory @ rb_sysopen - /home/tjn/.aws/aws-session-config.yml (Errno::ENOENT)
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/lib/aws/session/credentials/file_provider/yaml_file_provider.rb:28:in `open'
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/lib/aws/session/credentials/file_provider/yaml_file_provider.rb:28:in `write'
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/lib/aws/session/credentials/file_provider/yaml_file_provider.rb:14:in `[]='
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/lib/aws/session/credentials/config.rb:27:in `profiles_hash='
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/lib/aws/session/credentials/profile_storage.rb:31:in `profiles='
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/lib/aws/session/credentials/profile_storage.rb:45:in `set_profile'
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/lib/aws/session/credentials/cli.rb:177:in `configure'
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/tjn/.rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.4/exe/aws-session:4:in `<top (required)>'
        from /home/tjn/.rvm/gems/ruby-2.3.1/bin/aws-session:23:in `load'
        from /home/tjn/.rvm/gems/ruby-2.3.1/bin/aws-session:23:in `<main>'
        from /home/tjn/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/tjn/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by zl4bv** [comment]
@tjnicholas thanks for reporting the issue. A fix has been released in version 1.0.5.
